/**
 * The pt-BR pack for the report SCREENS — a NAMED constant a host passes by
 * hand, never a default.
 *
 * The filename is what exempts this file from the copy-portability gate:
 * Portuguese may ship, it may not be silent. Every sentence is VERBATIM what
 * the components used to render, so a host adopting it sees no change on
 * screen — what changes is that the words are chosen in a diff.
 */
import type { ReportScreensCopy } from "./screens-copy";

export const PT_BR_REPORT_SCREENS_COPY: ReportScreensCopy = {
  list: {
    title: "Relatórios",
    subtitle: "Seus painéis: escolha um para ver, ou monte outro com os blocos que quiser.",
    loadFailedTitle: "Não foi possível carregar os relatórios",
    loadFailedBody: "Tente novamente em instantes.",
    retry: "Tentar novamente",
    scopes: {
      active: "Todos",
      mine: "Meus",
      archived: "Arquivados",
    },
    search: "Buscar relatório",
    create: "Novo relatório",
    emptyTitle: "Nenhum relatório aqui.",
    emptyBody: "Monte o primeiro com receita por dia, top produtos e ticket médio.",
    emptySearchBody: "Tente outro termo.",
    chipDraft: "Rascunho",
    chipArchived: "Arquivado",
    chipUnpublished: "Alterações não publicadas",
    noDescription: "Sem descrição.",
    blockCount: (count) => `${count} ${count === 1 ? "bloco" : "blocos"}`,
    visibility: {
      private: "Só você",
      roles: "Cargos específicos",
      tenant: "Toda a equipe",
    },
    relativeTime: {
      now: "agora",
      minutes: (count) => `há ${count} min`,
      hours: (count) => `há ${count} ${count === 1 ? "hora" : "horas"}`,
      yesterday: "ontem",
      days: (count) => `há ${count} dias`,
      weeks: (count) => `há ${count} ${count === 1 ? "semana" : "semanas"}`,
    },
    edit: "Editar",
    archive: "Arquivar",
    restore: "Restaurar",
    cardMenu: (reportName) => `Mais ações de ${reportName}`,
    newCardTitle: "Novo relatório",
    newCardHint: "Comece de um modelo",
  },
  view: {
    noDescription: "Sem descrição.",
    visibleTo: (audience) => `visível para ${audience.toLocaleLowerCase("pt-BR")}`,
    editedAt: (relativeTime) => `editado ${relativeTime}`,
    breadcrumbList: "Relatórios",
    export: "Exportar",
    edit: "Editar",
    retry: "Tentar novamente",
    loadFailedTitle: "Não foi possível carregar o relatório",
    loadFailedBody: "Ele pode ter sido excluído, ou você não tem permissão.",
  },
  editor: {
    nameLabel: "Nome do relatório",
    namePlaceholder: "Relatório sem título",
    subtitle: (blocks, audience) => `${blocks} · ${audience}`,
    visibilityWords: {
      private: "só você",
      tenant: "toda a equipe",
      roles: "cargos específicos",
    },
    autosaving: "Salvando automaticamente…",
    autosaveFailed:
      "Não foi possível salvar automaticamente. Suas alterações continuam aqui.",
    saving: "Salvando…",
    save: "Salvar ⌘S",
    breadcrumbList: "Relatórios",
    breadcrumbEditing: "Editando",
    unsavedChanges: "Alterações não salvas",
    settings: "⚙ Ajustes",
    previewBanner: "Pré-visualização com dados reais",
    openFailedTitle: "Não foi possível abrir o editor",
    openFailedBody: "Verifique sua permissão ou tente novamente.",
    retry: "Tentar novamente",
    exitTitle: "Sair sem publicar?",
    exitPublishedBody:
      "Suas alterações estão guardadas, mas ainda não foram publicadas. Quem abre o relatório continua vendo a versão publicada até você salvar.",
    exitDraftBody:
      "Suas alterações estão guardadas, mas o relatório ainda não foi publicado. Ninguém mais vê estas alterações até você salvar.",
    exitConfirm: "Sair sem publicar",
    unpublishedTitle: "Alterações não publicadas",
    unpublishedBody:
      "Quem abre o relatório continua vendo a versão publicada. Salve para publicar estas alterações.",
    discard: "Descartar alterações",
    discarding: "Descartando…",
    discardTitle: "Descartar alterações não publicadas?",
    discardBody:
      "As alterações que você ainda não publicou serão perdidas e o relatório volta à versão publicada. Não dá para desfazer.",
    discardConfirm: "Descartar alterações",
    needsName: "Dê um nome ao relatório antes de salvar.",
    needsBlock: "Adicione ao menos um bloco ao relatório.",
    addBlock: "Adicionar bloco — gráfico, tabela ou indicador",
    addBlockLimit: (max) => `Limite de ${max} blocos por relatório.`,
    removeBlockTitle: "Remover bloco?",
    removeBlockBody:
      "O bloco sai do relatório. Você ainda pode cancelar a edição para desfazer tudo.",
    removeBlockConfirm: "Remover",
    blockRunFailed: "Não foi possível executar este bloco.",
    blockDragHint: "Arraste ou Alt+↑/↓",
    editBlock: "Editar bloco",
    removeBlock: "Remover bloco",
    rangeApply: "Aplicar",
    rangeCancel: "Cancelar",
    confirmCancel: "Cancelar",
    blockTitleLabel: "Título do bloco",
    moveUp: "Mover para cima",
    moveDown: "Mover para baixo",
    blockMenu: "Mais ações do bloco",
  },
  archive: {
    restoreAction: "Restaurar",
    restoreTitle: "Restaurar relatório?",
    restoreBody: "Ele volta para a lista de relatórios da loja.",
    archiveAction: "Arquivar",
    archiveTitle: "Arquivar relatório?",
    archiveBodyFromList:
      "Ele sai da lista de relatórios, mas nada é perdido — você pode restaurá-lo depois em “Arquivados”.",
    archiveBodyFromViewer:
      "Ele sai da lista de relatórios, mas nada é perdido — você pode restaurá-lo depois em “Mostrar arquivados”.",
    busy: "Aguarde…",
    reportMenu: "Ações do relatório",
  },
  ranges: {
    ranges: {
      today: "Hoje",
      "7d": "7 dias",
      "30d": "30 dias",
      month: "Este mês",
      custom: "Personalizado…",
    },
    grains: {
      day: "Dia",
      week: "Semana",
      month: "Mês",
    },
    emptyTitle: "Sem dados no período",
    emptyBody: "Nenhum registro encontrado para o período selecionado.",
    widen: (rangeLabel) => `Ver ${rangeLabel}`,
  },
  system: {
    blockFailed: "Não foi possível carregar este relatório.",
    dashboardMissingTitle: "Painel não encontrado",
    dashboardMissingBody:
      "Este painel não existe mais. Use o menu lateral para escolher outro.",
    reportFailedTitle: "Não foi possível carregar o relatório",
    reportFailedBody: "Verifique sua permissão ou tente novamente em instantes.",
    retry: "Tentar novamente",
  },
  builder: {
    emptySelection: "Selecione um bloco para editar",
    duplicateBlocked: (max) => `Limite de ${max} blocos por relatório.`,
    blockTitleLabel: "Título",
    blockTitleHelper: (autoTitle) => `Vazio = usa a descrição automática: “${autoTitle}”.`,
    untitledBlock: "Bloco sem título",
    copyOf: (title) => `${title} (cópia)`,
    viewAsChart: "Ver como gráfico",
    viewAsTable: "Ver como tabela",
    blockMenu: "Mais ações do bloco",
    closePanel: "Fechar painel",
    panelIdle: "Bloco",
    panelEditing: "Editando bloco",
    templateTitle: "Adicionar bloco",
    removeFilter: (position) => `Remover filtro ${position}`,
    removeMeasure: (position) => `Remover medida ${position}`,
    remove: "Remover",
    templateOption: (title, description) => `${title} — ${description}`,
    templateHint: "Comece de um modelo pronto — você ajusta tudo depois.",
    cancel: "Cancelar",
    heights: {
      auto: "Auto",
      "1": "Baixa",
      "2": "Média",
      "3": "Alta",
    },
    collection: "Coleção",
    height: "Altura",
    valuesPlaceholder: "Valores separados por vírgula",
    filterValues: (position) => `Filtro ${position} — valores`,
    filterFrom: (position) => `Filtro ${position} — de`,
    filterTo: (position) => `Filtro ${position} — até`,
    filterField: (position) => `Filtro ${position} — campo`,
    filterCondition: (position) => `Filtro ${position} — condição`,
    filterValue: (position) => `Filtro ${position} — valor`,
    rangeEnd: "Até",
    condition: "Condição",
    splitSeries: "Separar em séries",
    seriesBy: "Uma série por",
    groupBy: "Agrupar por",
    aggregation: "Agregação",
    visualization: "Visualização",
    widthHeading: "Largura",
    filtersHeading: "Filtros",
    measuresHeading: "Medidas",
    rangeStartPlaceholder: "De",
    fieldLabel: "Campo",
    axisLabel: "Eixo X",
    grainLabel: "Por",
    stacked: "Empilhado",
    duplicate: "Duplicar",
    exportCsv: "Exportar CSV",
    grouping: "Agrupamento",
    discard: "Descartar",
    statusLabel: "Status",
    nameLabel: "Nome",
    done: "Concluir",
    operators: {
      eq: "igual a",
      neq: "diferente de",
      in: "é um de",
      gte: "a partir de",
      lte: "até",
      between: "entre",
    },
    charts: {
      table: "Tabela",
      kpi: "Número",
      line: "Linha",
      bar: "Barras",
      area: "Área",
      pie: "Pizza",
      donut: "Rosca",
    },
    aggregations: {
      sum: "Soma",
      avg: "Média",
      count: "Contagem",
      count_distinct: "Contagem distinta",
      min: "Mínimo",
      max: "Máximo",
      p50: "Mediana (p50)",
      p90: "Percentil 90 (p90)",
      p95: "Percentil 95 (p95)",
      ratio: "Proporção (soma ÷ soma)",
    },
    needsRole:
      "Escolha ao menos uma função para compartilhar — ou mude a visibilidade para 'Somente autor e admins'.",
    rolesLoading: "Carregando funções…",
    rolesFailed:
      "Não foi possível carregar as funções. Recarregue a página e tente novamente antes de salvar.",
    rolesHeading: "Funções com acesso (autor e admins sempre veem):",
    rolesEmpty: "Nenhuma função disponível nesta loja.",
    moved: (label, position, total) => `${label} movido para a posição ${position} de ${total}`,
    period: "Período",
    breadcrumbAria: "Trilha de navegação",
    defaultRange: "Período padrão ao abrir",
    defaultRanges: {
      today: "Hoje",
      "7d": "Últimos 7 dias",
      "30d": "Últimos 30 dias",
      month: "Este mês",
    },
    customRange: "Período personalizado",
    quickRangesHeading: "Períodos rápidos",
    quickRanges: {
      today: "Hoje",
      yesterday: "Ontem",
      "this-week": "Esta semana",
      "last-7-days": "7 dias",
      "this-month": "Este mês",
      "last-30-days": "30 dias",
      "this-quarter": "Este trimestre",
      "this-year": "Este ano",
      "last-365-days": "365 dias",
    },
    dateFrom: "Data inicial",
    dateTo: "Data final",
    rangeIncomplete: "Informe as datas inicial e final do período.",
    rangeReversed: "A data final deve ser igual ou posterior à inicial.",
    rangeOverMax: (maxRangeDays) => `O período não pode exceder ${maxRangeDays} dias.`,
    backToList: "Relatórios",
  },
  settings: {
    title: "Ajustes do relatório",
    descriptionLabel: "Descrição",
    descriptionPlaceholder: "Para que serve este relatório?",
    descriptionHelper: "Aparece no card da lista — ajuda a equipe a achar o certo.",
    statusCards: {
      published: {
        title: "Publicado",
        description: "Aparece na lista para quem tem acesso.",
      },
      draft: {
        title: "Rascunho",
        description: "Só você vê, mesmo que compartilhado.",
      },
    },
    visibilityCards: {
      private: { title: "Só você", description: "Ninguém mais da loja vê." },
      tenant: {
        title: "Toda a equipe",
        description: "Qualquer pessoa com acesso ao admin da loja.",
      },
      roles: {
        title: "Cargos específicos",
        description:
          "Campos de custo continuam ocultos para quem não tem permissão, qualquer que seja o cargo.",
      },
    },
    scheduleLabel: "Envio automático",
    scheduleValue: "Enviar por e-mail toda segunda, 8h",
    scheduleReason: "Em breve (FUT-776) — ainda não é possível agendar o envio.",
    visibilityLabel: "Quem pode ver",
    close: "Fechar",
  },
};
