import {
  PT_BR_CONFIRM_ACTION_COPY,
  PT_BR_DATA_VIEWS_COPY,
} from '@12-apps/ui/pt-BR';

import type { RbacWebCopy } from './copy';

/**
 * The pt-BR pack — the exact sentences the two screens compiled in until copy
 * became required config. The filename is what exempts this file from the
 * copy-portability gate: Portuguese may ship, it may not be silent.
 */
export const PT_BR_RBAC_WEB_COPY: RbacWebCopy = {
  operationFailed: 'Não foi possível concluir a operação.',
  loading: 'Carregando…',
  permissionsLoadFailed: 'Não foi possível carregar suas permissões.',
  tabs: { roles: 'Papéis', team: 'Equipe' },
  dataViews: PT_BR_DATA_VIEWS_COPY,
  confirmAction: PT_BR_CONFIRM_ACTION_COPY,
  menuLabel: 'Ações',
  actionErrorTitle: 'Não foi possível concluir a ação',
  closeLabel: 'Fechar',
  permissionLabels: {
    domains: { roles: 'Papéis', team: 'Equipe' },
    actions: { read: 'Ver', manage: 'Gerenciar' },
  },
  rolesList: {
    title: 'Papéis',
    newRoleAction: 'Novo papel',
    searchPlaceholder: 'Buscar papel',
    loadFailed: 'Não foi possível carregar os papéis.',
    retryAction: 'Tentar novamente',
    aboutTitle: 'Sobre os papéis',
    aboutBody:
      'Os papéis do sistema já vêm prontos — você pode ajustar as permissões de cada um para a sua loja (exceto Proprietário). Crie também papéis personalizados combinando permissões do catálogo e atribua-os à sua equipe.',
    emptyState: 'Nenhum papel encontrado.',
    forbiddenTitle: 'Página não encontrada',
    forbiddenBody: 'O endereço acessado não existe ou não está disponível.',
    dialogTitles: {
      create: 'Novo papel',
      edit: (name) => `Editar ${name}`,
      override: (name) => `Editar papel do sistema ${name}`,
    },
    deleteConfirm: {
      title: 'Excluir o papel?',
      body: 'Quem tem este papel perde os acessos dele imediatamente.',
      confirmLabel: 'Excluir',
    },
    resetConfirm: {
      title: 'Restaurar padrão do papel?',
      body: 'As permissões voltam ao padrão do sistema. Esta ação não pode ser desfeita.',
      confirmLabel: 'Restaurar padrão',
    },
    cancelAction: 'Cancelar',
  },
  rolesTable: {
    headers: {
      name: 'Nome',
      description: 'Descrição',
      kind: 'Tipo',
      permissions: 'Permissões',
      actions: 'Ações',
    },
    kinds: { system: 'Sistema', systemEdited: 'Sistema · editado', custom: 'Personalizado' },
    kindFilter: 'Tipo',
    allPermissions: 'Todas',
    permissionsUnit: 'permissões',
    noDescription: 'sem descrição',
    editableLabel: 'Editável',
    editableYes: 'Sim',
    lockedLabel: 'Bloqueado',
    noPermissions: 'Nenhuma permissão',
    emptyValue: '—',
    editAction: 'Editar',
    resetAction: 'Restaurar padrão',
    deleteAction: 'Excluir',
    historyAction: 'Histórico de versões',
    deleteFailed: 'Não foi possível excluir o papel.',
    resetFailed: 'Não foi possível restaurar o padrão do papel.',
  },
  roleForm: {
    nameLabel: 'Nome do papel',
    descriptionPlaceholder: 'Descrição (opcional)',
    descriptionLabel: 'Descrição',
    selectionCount: (count) => `Permissões (${count} selecionada${count === 1 ? '' : 's'})`,
    kinds: { class: 'classe', instance: 'instância' },
    cancelAction: 'Cancelar',
    saveAction: 'Salvar',
    createAction: 'Criar papel',
  },
  teamScreen: {
    title: 'Equipe',
    searchPlaceholder: 'Buscar membro',
    loadFailed: 'Não foi possível carregar a equipe.',
    retryAction: 'Tentar novamente',
    aboutTitle: 'Sobre a equipe',
    aboutBody:
      'Gerencie os administradores desta loja. Você pode convidar por e-mail mesmo quem ainda não tem conta — o acesso é atribuído automaticamente quando a pessoa se cadastra.',
    inviteAction: 'Adicionar administrador',
    inviteDialogTitle: 'Adicionar administrador',
    inviteEmailLabel: 'E-mail do novo administrador',
    inviteHint:
      'Se a pessoa já tiver uma conta, o acesso é concedido na hora. Caso contrário, o convite fica pendente e o acesso é atribuído automaticamente quando ela criar a conta com esse e-mail.',
    inviteDeferredTitle: 'Convite registrado',
    inviteDeferredBody:
      'O acesso será concedido automaticamente quando a pessoa criar a conta.',
    errorTitle: 'Não foi possível atualizar a equipe',
    emptyState: 'Nenhum administrador cadastrado.',
    exportFileName: 'equipe',
    removeConfirm: {
      title: 'Remover da equipe?',
      body: 'A pessoa perde o acesso ao painel imediatamente. Para voltar, precisa de um novo convite.',
      confirmLabel: 'Remover',
    },
    cancelInviteConfirm: {
      title: 'Cancelar o convite?',
      body: 'O link enviado deixa de valer. Para convidar de novo, é preciso reenviar.',
      confirmLabel: 'Cancelar convite',
      cancelLabel: 'Voltar',
      failed: 'Não foi possível cancelar o convite.',
    },
    removeFailed: 'Não foi possível remover esta pessoa da equipe.',
    cancelAction: 'Cancelar',
  },
  teamTable: {
    headers: { name: 'Nome', email: 'E-mail', roles: 'Papéis', status: 'Status' },
    status: { active: 'Ativo', disabled: 'Desativado', pending: 'Pendente' },
    filters: { roles: 'Papéis', status: 'Status' },
    exportHeaders: {
      name: 'Nome',
      email: 'E-mail',
      role: 'Papel',
      customRoles: 'Papéis',
      status: 'Status',
    },
  },
  teamRoleDialog: {
    title: (member) => `Papéis de ${member}`,
    fallbackTitle: 'Editar papéis',
    systemGroupTitle: 'Papel do sistema (escolha um)',
    customGroupTitle: 'Papéis personalizados (opcional)',
    exactlyOneSystemRole: 'Selecione exatamente um papel do sistema.',
    cancelAction: 'Cancelar',
    saveAction: 'Salvar',
  },
  teamRowMenu: {
    editRoles: 'Editar papéis',
    activate: 'Ativar',
    deactivate: 'Desativar',
    remove: 'Remover',
    cancelInvite: 'Cancelar convite',
    noActions: 'Sem ações disponíveis',
  },
  memberProfile: {
    tabs: {
      details: 'Detalhes do usuário',
      actions: 'Ações do usuário',
      ai: 'IA em nome do usuário',
      items: 'Itens criados',
    },
    comingSoon: 'Este recurso estará disponível em breve.',
    fields: {
      baseRole: 'Papel base',
      customRoles: 'Papéis adicionais',
      memberSince: 'Membro desde',
      lastLogin: 'Último acesso',
    },
    emptyValue: '—',
    notFoundTitle: 'Membro não encontrado',
    notFoundBody: 'Este usuário não faz parte da equipe desta loja.',
    loadFailed: 'Não foi possível carregar o perfil.',
    retryAction: 'Tentar novamente',
    loading: 'Carregando…',
  },
};
