/**
 * The packaged service worker, as SOURCE (12-23).
 *
 * A worker cannot be a module a host imports: the browser fetches it as its own
 * top-level script, from the host's own origin, at a path whose directory bounds
 * its scope. So the package ships the TEXT and the host serves it — from the
 * manifest mount (`createApiPwa` answers it at the root, with
 * `Service-Worker-Allowed: /`) or written to a static `public/sw.js` in a build
 * step. Either way the CACHING RULES below travel with the package instead of
 * being retyped, subtly differently, in every app.
 *
 * ── THE RULE THIS FILE EXISTS FOR ──────────────────────────────────────────
 * Every hashed filename in a bundled SPA dies with the deploy that produced it,
 * and a history fallback serves `index.html` in place of a missing chunk — which
 * fails on the MIME TYPE rather than as a 404. That rejection reaches
 * `React.lazy` and renders the page BLANK.
 *
 * A NAIVE CACHE-FIRST WORKER MAKES THAT PERMANENT: it pins an old `index.html`
 * naming chunks the server no longer has, and the escape reload then runs
 * against the cache — reloading into the same stale document, forever. On an
 * INSTALLED app "please force-refresh" is advice the user cannot follow. Hence,
 * and non-negotiably:
 *
 *   navigation / the shell → NETWORK-FIRST, cache only as an offline fallback
 *   hashed assets          → cache-first (immutable), and an HTML answer is
 *                            NEVER stored under an asset URL
 *   the API                → never cached (a stale cart is a wrong total)
 *
 * The generated worker also refuses to cache a non-200, an opaque cross-origin
 * response, or anything for a non-GET request.
 */

export interface PwaServiceWorkerOptions {
  /**
   * Prefix for this app's caches, e.g. `storefront`. Two apps on one origin must
   * not share a cache name.
   */
  cachePrefix?: string;
  /**
   * Bumped when the CACHING BEHAVIOUR changes: a new version adopts fresh caches
   * and drops the old ones on activate. It is not a build id — hashed asset URLs
   * already do that job.
   */
  cacheVersion?: string;
  /** The document every SPA route resolves to (the history fallback's target). */
  shellUrl?: string;
  /** Path prefixes holding immutable, content-hashed build output. */
  assetPrefixes?: readonly string[];
  /** Path prefixes that must NEVER be cached (live state). */
  neverCachePrefixes?: readonly string[];
  /**
   * Scripts to `importScripts` first, same-origin only (a worker may load
   * scripts only from its own origin). This is the seam a host uses to add its
   * own layers — error reporting, push handling — without forking the caching
   * rules. Anything with a scheme or `//` is rejected at generation time, so a
   * config value cannot smuggle a third-party script into the worker scope.
   */
  importScripts?: readonly string[];
}

/** A same-origin, absolute path — the only thing the worker will import. */
function assertSameOriginPath(path: string): string {
  if (!path.startsWith("/") || path.startsWith("//") || /^[a-z][a-z0-9+.-]*:/i.test(path)) {
    throw new Error(
      `[pwa] importScripts entry must be a same-origin absolute path, got: ${path}`,
    );
  }
  return path;
}

/** JSON is a subset of JS literal syntax, so this is a safe embed. */
function literal(value: unknown): string {
  return JSON.stringify(value);
}

/**
 * The generated file's own header. Static: it explains the rules, and the rules
 * are not configurable — a host that wants different caching wants a different
 * worker, not this one with a flag.
 */
const WORKER_BANNER = `/**
 * Generated by @12-apps/pwa — pwaServiceWorkerSource(). Do not edit by hand:
 * the caching rules below are the package's, and a hand edit here is a rule
 * that exists in one app and no other.
 *
 * navigation/shell -> network-first (the cache is the OFFLINE fallback only)
 * hashed assets    -> cache-first, and an HTML answer is never stored
 * live paths       -> never cached
 *
 * A naive cache-first worker pins an old shell naming chunks the server no
 * longer has, and makes the resulting blank page permanent on an installed app.
 */`;

/**
 * The only part of the worker a host CONFIGURES: cache names, the shell URL and
 * the two prefix lists, emitted as literals the runtime below closes over.
 */
function workerConstants(options: PwaServiceWorkerOptions): string {
  const prefix = options.cachePrefix ?? "app";
  const version = options.cacheVersion ?? "v1";
  return [
    `const SHELL_CACHE = ${literal(`${prefix}-shell-${version}`)};`,
    `const ASSET_CACHE = ${literal(`${prefix}-assets-${version}`)};`,
    "const OUR_CACHES = [SHELL_CACHE, ASSET_CACHE];",
    `const CACHE_PREFIX = ${literal(`${prefix}-`)};`,
    `const SHELL_URL = ${literal(options.shellUrl ?? "/index.html")};`,
    `const ASSET_PREFIXES = ${literal(options.assetPrefixes ?? ["/assets/"])};`,
    `const NEVER_CACHE_PREFIXES = ${literal(options.neverCachePrefixes ?? ["/api/"])};`,
  ].join("\n");
}

/**
 * THE CACHING RULES, and they are static on purpose.
 *
 * Not a template with knobs: the network-first document strategy is the whole
 * reason this file exists (see the header above), so it is the one thing a host
 * cannot configure into the failure it prevents.
 */
const WORKER_RUNTIME = `self.addEventListener('install', (event) => {
  // Warm the shell so a first offline navigation has something to answer with.
  // A failure here must NOT abort the install: a failed install leaves the page
  // with no worker at all — and therefore not installable — which is far worse
  // than a cold cache.
  event.waitUntil(
    caches
      .open(SHELL_CACHE)
      .then((cache) => cache.add(SHELL_URL))
      .catch(() => undefined)
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  // Drop only OUR older caches. Another app on this origin owns its own prefix,
  // and anything a host layer added (a push-icon cache, say) is not ours to
  // sweep — hence the prefix test rather than a blanket keys() delete.
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith(CACHE_PREFIX) && !OUR_CACHES.includes(key))
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

function hasPrefix(pathname, prefixes) {
  return prefixes.some((prefix) => pathname.startsWith(prefix));
}

/**
 * Cache-first for immutable assets.
 *
 * A RESPONSE IS NOT CACHED BLINDLY: the history fallback answers a vanished
 * chunk with 200 text/html, and storing THAT would make the blank-page failure
 * permanent on this device instead of lasting until the next reload.
 */
async function assetFirst(request) {
  const cache = await caches.open(ASSET_CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;

  const response = await fetch(request);
  const contentType = response.headers.get('content-type') || '';
  if (
    response.status === 200 &&
    response.type !== 'opaque' &&
    !contentType.includes('text/html')
  ) {
    cache.put(request, response.clone()).catch(() => undefined);
  }
  return response;
}

/**
 * Network-first for documents, with the cached shell as the offline answer.
 *
 * This is the half that stops a deploy bricking an installed app: the network's
 * document always wins, so the one naming the CURRENT chunks is the one that
 * renders. The cache is reached only when the network is not — and it is stored
 * under the SHELL key, never the request URL, so one route can never be
 * answered with another route's baked content.
 */
async function documentNetworkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(SHELL_CACHE);
      cache.put(SHELL_URL, response.clone()).catch(() => undefined);
    }
    return response;
  } catch (error) {
    const cached = await caches.match(SHELL_URL);
    if (cached) return cached;
    throw error;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  // Only GET. A POST is a mutation and has no business in a cache.
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Somebody else's origin is somebody else's caching policy.
  if (url.origin !== self.location.origin) return;
  // Live state is never cached.
  if (hasPrefix(url.pathname, NEVER_CACHE_PREFIXES)) return;

  if (hasPrefix(url.pathname, ASSET_PREFIXES)) {
    event.respondWith(assetFirst(request));
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(documentNetworkFirst(request));
  }
});
`;

/**
 * Generate the worker source for one app.
 *
 * Deterministic for a given options object — a host may write it to disk at
 * build time and diff it, which is what makes a change to the caching rules
 * visible in review rather than only at runtime.
 */
export function pwaServiceWorkerSource(options: PwaServiceWorkerOptions = {}): string {
  const imports = (options.importScripts ?? []).map(assertSameOriginPath);
  return [
    WORKER_BANNER,
    imports.map((path) => `importScripts(${literal(path)});`).join("\n"),
    "",
    workerConstants(options),
    "",
    WORKER_RUNTIME,
  ].join("\n");
}
